// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApidemo.Models;

public partial class Studentstbl
{
    public int Stid { get; set; }

    public string Sname { get; set; }

    public int? Age { get; set; }
}