//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderId { get; set; }
        public string orddate { get; set; }
        public string product { get; set; }
        public string qty { get; set; }
        public int Customers_custId { get; set; }
    
        public virtual Customers Customer { get; set; }
    }
}
