//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public int pizzaid { get; set; }
        public string pname { get; set; }
        public string description { get; set; }
        public string pizzatype { get; set; }
        public string price { get; set; }
        public string toppings { get; set; }
    }
}
