// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MinimalAPIdemo.Models;

public partial class b248dbContext : DbContext
{
    public b248dbContext()
    {
    }

    public b248dbContext(DbContextOptions<b248dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Studentstbl> Studentstbls { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WKSBAN36SUHTR04\\SQLEXPRESS;Initial Catalog=b248db;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Studentstbl>(entity =>
        {
            entity.HasKey(e => e.Stid).HasName("PK__students__312D1FC7F810A682");

            entity.ToTable("studentstbl");

            entity.Property(e => e.Stid)
                .ValueGeneratedNever()
                .HasColumnName("stid");
            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.Sname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("sname");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}