//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace classLib
{
    using System;
    
    public enum CustomerType : int
    {
        Regular = 0,
        Preminum = 1,
        VIP = 2
    }
}
