//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace classLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public CustomerType CustomerType { get; set; }
        public System.DateTime Registeredon { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public int Age { get; set; }
    }
}
