// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarRentalApp.Models;

public partial class Customer
{
    public int CustomerId { get; set; }
    [Required(ErrorMessage = " pls enter Name")]
    public string Name { get; set; }
    [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email format")]
    public string Email { get; set; }
    [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be 10 digits")]
    public string Phone { get; set; }

    public string Address { get; set; }
    [Required(ErrorMessage = " pls enter License Number")]
    public string LicenseNumber { get; set; }
    [Required(ErrorMessage = " pls enter Username")]
    public string Username { get; set; }
    [Required(ErrorMessage = " pls enter Password  ")]
    public string Pwd { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}