// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalApp.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public int Year { get; set; }

    public string LicensePlate { get; set; }

    public string Carimage { get; set; }

    public string Fueltype { get; set; }

    public string Status { get; set; }

    public int? Rentperday { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();
}